### ISSUE TITLE
Hyperfunction support

### ISSUE THREAD

**Issue by davydog187** [bitfo/timescale#1]
- [x] [approximate_row_count](https://docs.timescale.com/api/latest/hyperfunctions/approximate_row_count/)
- [x] [first](https://docs.timescale.com/api/latest/hyperfunctions/first/)
- [x] [last](https://docs.timescale.com/api/latest/hyperfunctions/last/)
- [x] [histogram](https://docs.timescale.com/api/latest/hyperfunctions/histogram/)
- [x] [time_bucket](https://docs.timescale.com/api/latest/hyperfunctions/time_bucket/)
- [x] [time_bucket_ng](https://docs.timescale.com/api/latest/hyperfunctions/time_bucket_ng/)

**Comment by doomspork** [comment]
@davydog187 any thoughts on how best to handle `approximate_row_count` and the need for `ANALYZE` et al? Did you want to break out into other functions or as an opt on this?

**Comment by davydog187** [comment]
@doomspork I don't have strong feelings yet, if you're interested I'd love for you to suggest an API

**Comment by davydog187** [comment]
@doomspork I think the analyze piece should be part of the documentation. Any good managed Postgres should be running vacuum/analyze at some regular interval. We should just warn the users about that
