### ISSUE TITLE
SQL injection possible in create_hypertable/3

### ISSUE THREAD

**Issue by davydog187** [bitfo/timescale#11]
The risk here is so minimal because I doubt there's anyone creating tables from user input :) However, i do think we should be properly escaping any data into queries.

https://github.com/bitfo/timescale/blob/main/lib/timescale/migration.ex#L35

**Comment by akoutmos** [comment]
Leaving this issue open until we address the `enable_hypertable_compression` migration

- [ ] enabled_hypertable_compression
- [x] add_compression_policy
- [x] create_hypertable

**Comment by akoutmos** [comment]
Closing this one out in favor of https://github.com/bitfo/timescale/issues/4 as there is some work specific to `enabled_hypertable_compression` that needs to be done.
